name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.2.2

    - name: Build APK mit Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        workdir: .
        buildozer_version: stable

    - name: Upload APK Datei
      uses: actions/upload-artifact@v4.6.0
      with:
        name: android-apk
        path: bin/*.apk
